name: Run Crypto Bot

on:
  schedule:
    - cron: '*/15 * * * *'  # اجرای خودکار هر ۱۵ دقیقه
  workflow_dispatch:        # قابلیت اجرای دستی

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Main Script
      run: |
        python crypto-signals/main.py
